# -*- coding: utf-8 -*-
"""02_modeling_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QLlcnwrIkLl5ZM-x1EouMBkc6_hjgizH

# Demand Forecasting Model
"""

from google.colab import files
files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv('/content/cleaned_retail_inventory_data.csv')
df.head()

df['date'] = pd.to_datetime(df['date'])
df.dtypes

df = df.sort_values('date')  #to make timeline in right order

y = df['units_sold']  #target-y features - x

X = df[
    [
        'price',
        'discount',
        'competitor_pricing',
        'inventory_level',
        'holiday_promotion'
    ]
]

split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

X_train.shape, X_test.shape

"""Baseline model - Random Forest)"""

from sklearn.ensemble import RandomForestRegressor    #import model and metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

rf_model = RandomForestRegressor(   #initializing model
    n_estimators=100,
    random_state=42
)

#train
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

#evaluation
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

mae, rmse

df['units_sold'].describe()

#adding lag feature
df = df.sort_values('date')

df['lag_1_units_sold'] = df['units_sold'].shift(1) #yesterday’s demand as a feature

df = df.dropna().reset_index(drop=True)

X = df[
    [
        'price',
        'discount',
        'competitor_pricing',
        'inventory_level',
        'holiday_promotion',
        'month',
        'lag_1_units_sold'
    ]
]

y = df['units_sold']

#recreating time based split
split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

rf_model_v3 = RandomForestRegressor(
    n_estimators=300,
    max_depth=15,
    random_state=42
)

rf_model_v3.fit(X_train, y_train)

y_pred_v3 = rf_model_v3.predict(X_test)

mae_v3 = mean_absolute_error(y_test, y_pred_v3)
rmse_v3 = np.sqrt(mean_squared_error(y_test, y_pred_v3))

mae_v3, rmse_v3

"""Advanced model - XGBoost"""

!pip install xgboost

from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Ensure data is sorted by date
df = df.sort_values('date')

# Define features and target
X = df[
    [
        'price',
        'discount',
        'competitor_pricing',
        'inventory_level',
        'holiday_promotion',
        'lag_1_units_sold'
    ]
]

y = df['units_sold']

# Time-based split (80% train, 20% test)
split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

X_train.shape, X_test.shape

xgb_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42
)

xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_test)

mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))

mae_xgb, rmse_xgb

#adding relative price
# Relative price feature (our price vs competitor)
df['relative_price'] = df['price'] - df['competitor_pricing']

df[['price', 'competitor_pricing', 'relative_price']].head()

df = df.sort_values('date')

X = df[
    [
        'price',
        'discount',
        'competitor_pricing',
        'relative_price',
        'inventory_level',
        'holiday_promotion',
        'lag_1_units_sold'
    ]
]

y = df['units_sold']

split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

X_train.shape, X_test.shape

xgb_model_rp = XGBRegressor(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='reg:squarederror',
    random_state=42
)

xgb_model_rp.fit(X_train, y_train)

y_pred_xgb_rp = xgb_model_rp.predict(X_test)

mae_xgb_rp = mean_absolute_error(y_test, y_pred_xgb_rp)
rmse_xgb_rp = np.sqrt(mean_squared_error(y_test, y_pred_xgb_rp))

mae_xgb_rp, rmse_xgb_rp

import joblib

joblib.dump(xgb_model, "final_xgboost_model.pkl")

df_encoded = pd.get_dummies(
    df,
    columns=['weather_condition', 'seasonality'],
    drop_first=True
)

df[['weather_condition', 'seasonality']].head()

[col for col in df_encoded.columns if 'weather' in col or 'seasonality' in col][:10]

base_features = [
    'price',
    'discount',
    'competitor_pricing',
    'inventory_level',
    'holiday_promotion',
    'lag_1_units_sold'
]

context_features = [
    col for col in df_encoded.columns
    if col.startswith('weather_condition_') or col.startswith('seasonality_')
]
feature_cols = base_features + context_features

len(feature_cols), feature_cols[:10]

X = df_encoded[feature_cols]
y = df_encoded['units_sold']

df_encoded = df_encoded.sort_values('date')

split_index = int(len(df_encoded) * 0.8)

X_train = X.iloc[:split_index]
X_test  = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test  = y.iloc[split_index:]

X_train.shape, X_test.shape

X_train = X_train.astype(float)
X_test  = X_test.astype(float)

X_test = X_test[X_train.columns]

y_pred = xgb_model.predict(X_test.values)


from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

mae, rmse

print(X_train.shape)
print(X_test.shape)

X_train.dtypes.value_counts()